auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: Hyper Hamster
url: http://rbliu.github.io
feed: /atom.xml
author_info: <a href="http://rbliu.github.io/">rbliu</a>
