auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:categories/:title

name: "Robert's Blog"
title: Robert Liu's Blog
description: Everything about Robert Liu
url: http://rbliu.github.io
feed: /atom.xml
author_info: <a href="http://rbliu.github.io/">rbliu</a>
